# longhorn-ui-ingress.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`longhorn.kwadwolabs.cloud`)
    kind: Rule
    services:
      - name: longhorn-frontend
        port: http
  tls:
    certResolver: myresolver
