apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator-config
  namespace: trivy-system
data:
  TRIVY_SEVERITY: "HIGH,CRITICAL"
  TRIVY_IGNORE_UNFIXED: "true"
  TRIVY_TIMEOUT: "5m"
  OPERATOR_LOG_DEV_MODE: "false"
  OPERATOR_SCAN_JOB_TTL: "1h"
