apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-operator-config
  namespace: trivy-system
data:
  IMAGE_PULL_SECRET: "regcred"
  TRIVY_SEVERITY: "HIGH,CRITICAL"
  TRIVY_IGNORE_UNFIXED: "true"
  TRIVY_TIMEOUT: "5m"
  OPERATOR_LOG_DEV_MODE: "false"
  OPERATOR_SCAN_JOB_TTL: "1h"
  SCAN_JOB_MEMORY_LIMIT: "1536Mi"  # Set limit to 1.5 GiB
  SCAN_JOB_MEMORY_REQUEST: "1024Mi" # Request 1.0 GiB
  SCAN_JOB_CPU_LIMIT: "1000m"      # Limit to 1 CPU core
  SCAN_JOB_CPU_REQUEST: "500m" 
