resources:
  requests:
    cpu: 50m
    memory: 128Mi
config:
  clients:
    - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push  # Points to Loki service
  snippets:
    pipelineStages:
      - docker: {}
      - cri: {}
    scrapeConfigs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: __service__
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: hostname
        pipeline_stages:
          - docker: {}
daemonset:
  enabled: true