# grafana-ui-ingress.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ui
  namespace: logging
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`grafana.kwadwolabs.cloud`)
    kind: Rule
    services:
      - name: grafana
        port: http
  tls:
    certResolver: myresolver