apiVersion: v1
kind: Service
metadata:
  name: loki-external
  namespace: logging
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: single-binary
  ports:
    - name: http-metrics
      port: 3100
      targetPort: 3100
      nodePort: 31000 # We fix this port so it's easy to remember
