---
- name: Include common installation tasks
  ansible.builtin.include_tasks: install_common.yml

- name: Include control plane tasks
  ansible.builtin.include_tasks: control_plane.yml

- name: Include worker node tasks
  ansible.builtin.include_tasks: worker_node.yml
