apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-config
  namespace: sonarqube
data:
  SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres-0.postgres.sonarqube.svc.cluster.local:5432/sonarqube"
