apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarqube-ingress
  namespace: sonarqube
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarqube.kwadwolabs.cloud`)
      kind: Rule
      services:
        - name: sonarqube
          port: 9000
  tls:
    certResolver: myresolver